import ts from 'typescript';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const root = new URL('../../', import.meta.url);
const names = ['pasteStructureClassifier', 'pasteAsOrg2', 'pasteClipboardHtml'];
const modules = names.map(name => {
  const source = readFileSync(new URL(`src/${name}.ts`, root), 'utf8');
  const { outputText } = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS } });
  return `${JSON.stringify('./' + name + '.js')}: (exports, require) => {\n${outputText}\n}`;
});
const model = readFileSync(new URL('tools/paste-as-org2/model.json', root), 'utf8').trim();
const output = `// Generated by tools/paste-as-org2/build-native.mjs. Do not edit.\n(() => {\nconst factories = {${modules.join(',\n')}};\nconst cache = {};\nconst require = name => { if (!cache[name]) { cache[name] = {}; factories[name](cache[name], require); } return cache[name]; };\nconst {createPastePreview} = require('./pasteAsOrg2.js');\nconst {extractPasteHtml} = require('./pasteClipboardHtml.js');\nconst {validatePasteModel} = require('./pasteStructureClassifier.js');\nconst model = validatePasteModel(${model});\nglobalThis.openOrgPastePreview = input => createPastePreview({ ...input, semantic: input.html ? extractPasteHtml(input.html, document) : undefined, model: input.useModel ? model : undefined });\n})();\n`;
const target = new URL('apps/macos/Org2Workspace/Sources/Org2WorkspaceCore/Resources/PasteAsOrg2.js', root);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) throw new Error('PasteAsOrg2.js is stale; run npm run build:paste-native');
} else writeFileSync(target, output);
console.log(`Verified native paste runtime: ${fileURLToPath(target)}`);
