import AppKit
import XCTest
@testable import Org2WorkspaceCore

final class OrgCodeHighlighterTests: XCTestCase {
  private struct ParityFixture: Decodable {
    let language: String
    let source: String
    let tokens: [[ParityValue]]
  }

  private enum ParityValue: Decodable {
    case string(String)
    case int(Int)

    init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let value = try? container.decode(Int.self) { self = .int(value) } else { self = .string(try container.decode(String.self)) }
    }

    var string: String? { if case .string(let value) = self { value } else { nil } }
    var int: Int? { if case .int(let value) = self { value } else { nil } }
  }

  func testLanguageTableLoadsFromTheSharedGeneratedResource() throws {
    let table = try XCTUnwrap(OrgCodeHighlighter.table)
    XCTAssertEqual(table.schema, "org2:code-language-table:v1")
    XCTAssertGreaterThanOrEqual(table.languages.count, 60)
    for language in table.languages.keys {
      XCTAssertNotNil(OrgCodeHighlighter.compiledLanguage(language), language)
    }
  }

  func testPathDetectionMatchesTheSharedSourceLanguageRules() {
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/tool.py"), "python")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/README.md"), "markdown")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/main.tf"), "hcl")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/CMakeLists.txt"), "cmake")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/.gitignore"), "gitignore")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/Dockerfile"), "dockerfile")
    XCTAssertEqual(OrgCodeHighlighter.language(forPath: "/repo/.env.local"), "shell")
    XCTAssertNil(OrgCodeHighlighter.language(forPath: "/notes/a.org"))
    XCTAssertNil(OrgCodeHighlighter.language(forPath: "/notes/a.org2"))
    XCTAssertNil(OrgCodeHighlighter.language(forPath: "/notes/data.csv"))
    XCTAssertNil(OrgCodeHighlighter.language(forPath: "/notes/notes.txt"), "plain text keeps the ordinary editor")
  }

  /// The native tokenizer reproduces the shared TypeScript tokenizer's typed
  /// tokens for the fixture generated by tools/generate-code-languages.mjs.
  func testNativeTokensMatchTheSharedTokenizer() throws {
    let fixtureURL = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent() // this file
      .deletingLastPathComponent() // Org2WorkspaceCoreTests
      .deletingLastPathComponent() // Tests
      .deletingLastPathComponent() // Org2Workspace
      .deletingLastPathComponent() // macos
      .deletingLastPathComponent() // apps
      .appendingPathComponent("test/fixtures/code-highlight-parity.json")
    let fixtures = try JSONDecoder().decode([ParityFixture].self, from: Data(contentsOf: fixtureURL))
    XCTAssertGreaterThanOrEqual(fixtures.count, 10)
    for fixture in fixtures {
      let expected = fixture.tokens.compactMap { values -> String? in
        guard values.count == 3, let kind = values[0].string, let location = values[1].int, let length = values[2].int else { return nil }
        return "\(kind)@\(location)+\(length)"
      }
      let actual = OrgCodeHighlighter.tokens(in: fixture.source, language: fixture.language)
        .map { "\($0.kind.rawValue)@\($0.range.location)+\($0.range.length)" }
      XCTAssertEqual(actual, expected, fixture.language)
    }
  }

  func testApplyingCodeHighlightingStylesTokensWithoutChangingText() {
    let source = "def f():\n    return 1  # done\n"
    let storage = NSTextStorage(string: source)
    let base = OrgSyntaxHighlighter.baseTypingAttributes(monospaced: true)
    OrgCodeHighlighter.apply(to: storage, language: "python", baseAttributes: base)
    XCTAssertEqual(storage.string, source)
    let keywordColor = storage.attribute(.foregroundColor, at: 0, effectiveRange: nil) as? NSColor
    XCTAssertEqual(keywordColor, OrgCodeHighlighter.color(for: .keyword))
    let commentLocation = (source as NSString).range(of: "# done").location
    XCTAssertEqual(storage.attribute(.foregroundColor, at: commentLocation, effectiveRange: nil) as? NSColor, OrgCodeHighlighter.color(for: .comment))

    // Incremental restyling of one line keeps multi-line context.
    let block = "x = \"\"\"a\nb\"\"\"\ny = 2\n"
    let blockStorage = NSTextStorage(string: block)
    OrgCodeHighlighter.apply(to: blockStorage, language: "python", characterRange: NSRange(location: 9, length: 0), baseAttributes: base)
    XCTAssertEqual(blockStorage.attribute(.foregroundColor, at: 9, effectiveRange: nil) as? NSColor, OrgCodeHighlighter.color(for: .string))
  }
}
